name: Сборка и публикация Docker образа

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    name: Сборка и публикация образа
    runs-on: ubuntu-latest

    steps:
      # 1) Получение кода
      - name: Загрузка кода
        uses: actions/checkout@v3

      # 2) Проверка Python кода
      - name: Проверка кода flake8
        run: |
          pip install flake8
          flake8 app.py --count --show-source --statistics

      # 3) Запуск теста приложения
      - name: Тестирование приложения
        run: |
          python app.py | grep "Hello, World!" || exit 1

      # 4) Проверка Dockerfile
      - name: Проверка Dockerfile
        run: docker build --quiet --file ./Dockerfile .

      # 5) Авторизация в Docker Hub (только при push в main)
      - name: Вход в Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6) Сборка и публикация
      - name: Сборка и публикация образа
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: "${{ github.event_name == 'push' }}"
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/repo:latest
            ${{ secrets.DOCKER_USERNAME }}/repo:${{ github.sha }}
